model : 'NCF'
# 경로 설정
data_path: "./data/rating_complete.csv"

# 모델 파라미터
learning_rate : 0.001
batch_size : 1024
epochs : 1
loss: "MSELoss"

NCF:
  factor_num: 3
  num_layers: 2
  dropout: 0.2
  embedding_size : 128
  
mlflow:
  tracking_uri: server:port