cuda_visible_devices: 0

model : SASRec
data_path: "./data"
export_path: "./data/processed"

dataset:
  max_length: 50
  # num_negatives:
  full_negative_sampling: False

dataloader:
  batch_size: 128
  test_batch_size: 256
  num_workers: 8
  valid_size: 10000

seqrec_module:
  lr: 0.001
  predict_top_k: 10
  filter_seen: True
  # loss: bce

NCF:
  factor_num: 3
  num_layers: 2
  dropout: 0.2
  embedding_size : 128
SASRec:
  maxlen: 200
  hidden_units: 64
  num_blocks: 2
  num_heads: 1
  dropout_rate: 0.1

patience: 10
sampled_metrics: False
top_k_metrics: [10, 100]
epochs: 100
  
mlflow:
  tracking_uri: server:port