cuda_visible_devices: 0

model : SASRec
data_path: "./data"
export_path: "./data/processed"

dataset:
  max_length: 50
  # num_negatives:
  negative_sample: 
    type: "" # "popularity", "full", "" -> 빈값 처리 X
    pop_type: "rank" # "rank-prob","count-prob","rank" Only used in popularity
    weight_type: "top" # "top", "bot","mid" Only used in popularity

dataloader:
  batch_size: 128
  test_batch_size: 256
  num_workers: 8
  valid_size: 10000

seqrec_module:
  lr: 0.001
  predict_top_k: 10
  filter_seen: True
  loss: sim_rec # bce, cross_entropy, sim_rec
  lambda_value: 0.5 # only for sim_rec
  similarity_threshold: 0.9 # only for sim_rec
  similarity_indicies: "./save/models/ml-20m-similarity-indices-thenlper_gte-large.pt" # only for sim_rec
  similarity_value: "./save/models/ml-20m-similarity-values-thenlper_gte-large.pt" # only for sim_rec
  temperature: 1 # only for sim_rec
NCF:
  factor_num: 3
  num_layers: 2
  dropout: 0.2
  embedding_size : 128
SASRec:
  maxlen: 200
  hidden_units: 64
  num_blocks: 2
  num_heads: 1
  dropout_rate: 0.1

patience: 10
sampled_metrics: False
top_k_metrics: [10, 100]
epochs: 100
  
mlflow:
  # run_name: 
  tracking_uri: server:port
  description: |
    mlflow description 작성해주세요.
    들여쓰기만 맞추면 됩니다.
  user : YDS
  